version: '3.10'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - media_files:/app/media
    ports:
      - "9000:9000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    env_file:
      - .env
  celery:
    container_name: search_engine_celery
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
  celery-beat:
    container_name: search_engine_celery_beat
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  local_postgres_data:
  media_files:
