version: '3.10'

services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
      - media_files:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

volumes:
  local_postgres_data:
  media_files:
