# Generated by Django 3.2.7 on 2022-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные курса валют')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курс валют',
            },
        ),
        migrations.CreateModel(
            name='SearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('search_id', models.UUIDField(editable=False, verbose_name='ID поиска')),
                ('url', models.URLField(verbose_name='URL сервиса')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('NO_DATA', 'NO_DATA')], default='PENDING', max_length=9, verbose_name='Статус')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Результат поиска')),
            ],
            options={
                'verbose_name': 'Результат поиска',
                'verbose_name_plural': 'Результаты поиска',
            },
        ),
    ]
