# Generated by Django 3.2.7 on 2022-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('NO_DATA', 'NO_DATA')], default='PENDING', max_length=9, verbose_name='Статус'),
        ),
    ]
