# Generated by Django 3.2.7 on 2022-08-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0002_searchresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency',
            new_name='ExchangeRate',
        ),
    ]
